/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package chatClient

import java.io.File

fun main(args: Array<String>) {
    val file = File("user.xml")
    if (!file.exists()) file.createNewFile()

    if (file.length().toInt() == 0) {
        Register()
    } else {
        SelectFriend()
    }
}
