package chatClient

import java.awt.Color
import java.awt.Dimension
import java.awt.Insets
import javax.swing.*

class Chat(friend: String) {
    private var frame = JFrame("Chat with $friend")
    private var panel = JPanel()
    private var list = JList<String>()
    private var textField = JTextField()
    private var sendButton = JButton("send")

    private var db = Database()
    private var crypto = Crypto()

    // your info
    private val userData = Xml().readXml("user.xml")
    private val user = userData[0]
    private val userPublicKey = crypto.base64ToPublicKey(userData[1])
    private val userPrivateKey = crypto.base64ToPrivateKey(userData[2])
    // friends info
    private val friend = friend
    private val friendPublicKey = crypto.base64ToPublicKey(
        db.findUserByName(friend)["publicKey"].asString
    )

    // thread to refresh chat in background
    private val thread = Thread {
        while (true) {
            Thread.sleep(5000)
            val messages = db.findMessageByIdFromAndIdFor(user, friend)
            if (list.model.size != messages.size()) fillList()
        }
    }

    init {
        // all generated by Intellij GUI designer
        panel.layout = com.intellij.uiDesigner.core.GridLayoutManager(
            2, 2,
            Insets(0, 0, 0, 0),
            -1, -1
        )
        panel.preferredSize = Dimension(250, 400)
        panel.add(
            list,
            com.intellij.uiDesigner.core.GridConstraints(
                0, 0, 1, 2,
                com.intellij.uiDesigner.core.GridConstraints.ANCHOR_CENTER,
                com.intellij.uiDesigner.core.GridConstraints.FILL_BOTH,
                com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_WANT_GROW,
                com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_WANT_GROW,
                null,
                Dimension(150, 50),
                null,
                0,
                false
            )
        )
        panel.add(
            textField,
            com.intellij.uiDesigner.core.GridConstraints(
                1, 0, 1, 1,
                com.intellij.uiDesigner.core.GridConstraints.ANCHOR_WEST,
                com.intellij.uiDesigner.core.GridConstraints.FILL_HORIZONTAL,
                com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_WANT_GROW,
                com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED,
                null,
                Dimension(150, -1),
                null,
                0,
                false
            )
        )
        panel.add(
            sendButton,
            com.intellij.uiDesigner.core.GridConstraints(
                1, 1, 1, 1,
                com.intellij.uiDesigner.core.GridConstraints.ANCHOR_CENTER,
                com.intellij.uiDesigner.core.GridConstraints.FILL_HORIZONTAL,
                com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_SHRINK or com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_GROW,
                com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED,
                null,
                null,
                null,
                0,
                false
            )
        )

        thread.start()

        // my code
        frame.minimumSize = Dimension(250,300)
        frame.add(panel)
        frame.defaultCloseOperation = JFrame.EXIT_ON_CLOSE
        frame.pack()
        frame.isVisible = true

        lookAndFeel()
        fillList()

        // action listeners
        sendButton.addActionListener {
            val message = textField.text
            if (message == "") return@addActionListener

            try {
                db.sendMessage(friend, user,
                    crypto.encrypt("$user: $message", userPublicKey)
                )
                // save message twice so you can decrypt what you have send to others
                // with you own private key
                if (user != friend) {
                    db.sendMessage(user, friend,
                        crypto.encrypt("$user: $message", friendPublicKey)
                    )
                }
            } catch (e: Exception) {}

            textField.text = ""
            fillList()
        }
    }

    private fun fillList() {
        val chat = DefaultListModel<String>()
        val messages = db.findMessageByIdFromAndIdFor(friend, user)
        for (m in messages) {
            val encrypted = m.asJsonObject["message"].asString
            chat.addElement(crypto.decrypt(
                encrypted, userPrivateKey)
            )
        }
        list.model = chat
    }

    private fun lookAndFeel() {
        list.background = Color(58, 191, 54)
        panel.background = Color(58, 191, 54)
        sendButton.background = Color(88, 22, 89)
        sendButton.foreground = Color.WHITE
        frame.foreground = Color(38, 37, 38)
    }
}